[package]
name = "assembler"
version = "0.1.0"
authors = ["Rico Meinl <rmeinl97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.3"
simple-error = "0.2"
lazy_static = "1.3.0"